server:
  port: 8801

spring:
  application:
    name: provider-server

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8805


